version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/employee-app

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: ec2-user

  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: ec2-user


  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user

  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
      runas: ec2-user

