version: 0.0
os: linux

# Copy files from repo to EC2
files:
  - source: /
    destination: /home/ec2-user/employee-app

# Run scripts at different deployment stages
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      runas: ec2-user
  AfterInstall:
    - location: scripts/install.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      runas: ec2-user

